version: "3.7"
services:

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/redpanda.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3001:3000
    links:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: unless-stopped
    expose:
      - 9100

  redpanda:
    image: docker.vectorized.io/vectorized/redpanda:latest
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '0'
    - --check=false
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda:29092,OUTSIDE://redpanda:9092
    - --pandaproxy-addr
    - 0.0.0.0:8082
    - --advertise-pandaproxy-addr
    - redpanda:8082
    # NOTE: Please use the latest version here!
    ports:
    - 8082:8082
    - 9092:9092
    - 9644:9644
    - 29092:29092
    volumes:
      - redpanda:/var/lib/redpanda/data:rw

volumes:
  redpanda:
